version: '3.8'

services:
  whatsapp-bot:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app
      - ./src/sessions:/usr/src/app/sessions
    environment:
      - PORT=3000
